// Code generated by MockGen. DO NOT EDIT.
// Source: real-time-activity-feed/internal/module/feed/application (interfaces: BroadcastService)
//
// Generated by this command:
//
//	mockgen -destination=../infrastructure/mocks/broadcast_service_mock.go -package=mocks real-time-activity-feed/internal/module/feed/application BroadcastService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "real-time-activity-feed/internal/module/feed/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBroadcastService is a mock of BroadcastService interface.
type MockBroadcastService struct {
	ctrl     *gomock.Controller
	recorder *MockBroadcastServiceMockRecorder
	isgomock struct{}
}

// MockBroadcastServiceMockRecorder is the mock recorder for MockBroadcastService.
type MockBroadcastServiceMockRecorder struct {
	mock *MockBroadcastService
}

// NewMockBroadcastService creates a new mock instance.
func NewMockBroadcastService(ctrl *gomock.Controller) *MockBroadcastService {
	mock := &MockBroadcastService{ctrl: ctrl}
	mock.recorder = &MockBroadcastServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBroadcastService) EXPECT() *MockBroadcastServiceMockRecorder {
	return m.recorder
}

// BroadcastEvent mocks base method.
func (m *MockBroadcastService) BroadcastEvent(ctx context.Context, entry *domain.FeedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BroadcastEvent", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// BroadcastEvent indicates an expected call of BroadcastEvent.
func (mr *MockBroadcastServiceMockRecorder) BroadcastEvent(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastEvent", reflect.TypeOf((*MockBroadcastService)(nil).BroadcastEvent), ctx, entry)
}

// SubscribeToFeedEvents mocks base method.
func (m *MockBroadcastService) SubscribeToFeedEvents(ctx context.Context) (<-chan *domain.FeedEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeToFeedEvents", ctx)
	ret0, _ := ret[0].(<-chan *domain.FeedEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeToFeedEvents indicates an expected call of SubscribeToFeedEvents.
func (mr *MockBroadcastServiceMockRecorder) SubscribeToFeedEvents(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeToFeedEvents", reflect.TypeOf((*MockBroadcastService)(nil).SubscribeToFeedEvents), ctx)
}
