// Code generated by MockGen. DO NOT EDIT.
// Source: real-time-activity-feed/internal/module/feed/application (interfaces: UserRepository,FeedRepository,FeedCache)
//
// Generated by this command:
//
//	mockgen -destination=../infrastructure/mocks/repository_mock.go -package=mocks real-time-activity-feed/internal/module/feed/application UserRepository,FeedRepository,FeedCache
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "real-time-activity-feed/internal/module/feed/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// GetByIDs mocks base method.
func (m *MockUserRepository) GetByIDs(ctx context.Context, userIDs []string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ctx, userIDs)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockUserRepositoryMockRecorder) GetByIDs(ctx, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockUserRepository)(nil).GetByIDs), ctx, userIDs)
}

// MockFeedRepository is a mock of FeedRepository interface.
type MockFeedRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFeedRepositoryMockRecorder
	isgomock struct{}
}

// MockFeedRepositoryMockRecorder is the mock recorder for MockFeedRepository.
type MockFeedRepositoryMockRecorder struct {
	mock *MockFeedRepository
}

// NewMockFeedRepository creates a new mock instance.
func NewMockFeedRepository(ctrl *gomock.Controller) *MockFeedRepository {
	mock := &MockFeedRepository{ctrl: ctrl}
	mock.recorder = &MockFeedRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedRepository) EXPECT() *MockFeedRepositoryMockRecorder {
	return m.recorder
}

// CreateEvent mocks base method.
func (m *MockFeedRepository) CreateEvent(ctx context.Context, entry domain.FeedEvent) (*domain.FeedEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvent", ctx, entry)
	ret0, _ := ret[0].(*domain.FeedEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEvent indicates an expected call of CreateEvent.
func (mr *MockFeedRepositoryMockRecorder) CreateEvent(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvent", reflect.TypeOf((*MockFeedRepository)(nil).CreateEvent), ctx, entry)
}

// GetFeed mocks base method.
func (m *MockFeedRepository) GetFeed(ctx context.Context, eventType, query string, limit, offset int64) ([]domain.FeedEvent, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeed", ctx, eventType, query, limit, offset)
	ret0, _ := ret[0].([]domain.FeedEvent)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetFeed indicates an expected call of GetFeed.
func (mr *MockFeedRepositoryMockRecorder) GetFeed(ctx, eventType, query, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeed", reflect.TypeOf((*MockFeedRepository)(nil).GetFeed), ctx, eventType, query, limit, offset)
}

// MockFeedCache is a mock of FeedCache interface.
type MockFeedCache struct {
	ctrl     *gomock.Controller
	recorder *MockFeedCacheMockRecorder
	isgomock struct{}
}

// MockFeedCacheMockRecorder is the mock recorder for MockFeedCache.
type MockFeedCacheMockRecorder struct {
	mock *MockFeedCache
}

// NewMockFeedCache creates a new mock instance.
func NewMockFeedCache(ctrl *gomock.Controller) *MockFeedCache {
	mock := &MockFeedCache{ctrl: ctrl}
	mock.recorder = &MockFeedCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedCache) EXPECT() *MockFeedCacheMockRecorder {
	return m.recorder
}

// GetFeed mocks base method.
func (m *MockFeedCache) GetFeed(ctx context.Context, eventType string, limit, offset int64) ([]domain.FeedEvent, int64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeed", ctx, eventType, limit, offset)
	ret0, _ := ret[0].([]domain.FeedEvent)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetFeed indicates an expected call of GetFeed.
func (mr *MockFeedCacheMockRecorder) GetFeed(ctx, eventType, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeed", reflect.TypeOf((*MockFeedCache)(nil).GetFeed), ctx, eventType, limit, offset)
}

// InvalidateAfterPublish mocks base method.
func (m *MockFeedCache) InvalidateAfterPublish(ctx context.Context, eventType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateAfterPublish", ctx, eventType)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateAfterPublish indicates an expected call of InvalidateAfterPublish.
func (mr *MockFeedCacheMockRecorder) InvalidateAfterPublish(ctx, eventType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateAfterPublish", reflect.TypeOf((*MockFeedCache)(nil).InvalidateAfterPublish), ctx, eventType)
}

// SetFeed mocks base method.
func (m *MockFeedCache) SetFeed(ctx context.Context, eventType string, limit, offset int64, entries []domain.FeedEvent, total int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFeed", ctx, eventType, limit, offset, entries, total)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFeed indicates an expected call of SetFeed.
func (mr *MockFeedCacheMockRecorder) SetFeed(ctx, eventType, limit, offset, entries, total any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFeed", reflect.TypeOf((*MockFeedCache)(nil).SetFeed), ctx, eventType, limit, offset, entries, total)
}
