// Code generated by MockGen. DO NOT EDIT.
// Source: real-time-activity-feed/internal/module/feed/application (interfaces: EventPublisherUseCase)
//
// Generated by this command:
//
//	mockgen -destination=../adapters/mocks/event_publisher_usecase_mock.go -package=mocks real-time-activity-feed/internal/module/feed/application EventPublisherUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	application "real-time-activity-feed/internal/module/feed/application"
	domain "real-time-activity-feed/internal/module/feed/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEventPublisherUseCase is a mock of EventPublisherUseCase interface.
type MockEventPublisherUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherUseCaseMockRecorder
	isgomock struct{}
}

// MockEventPublisherUseCaseMockRecorder is the mock recorder for MockEventPublisherUseCase.
type MockEventPublisherUseCaseMockRecorder struct {
	mock *MockEventPublisherUseCase
}

// NewMockEventPublisherUseCase creates a new mock instance.
func NewMockEventPublisherUseCase(ctrl *gomock.Controller) *MockEventPublisherUseCase {
	mock := &MockEventPublisherUseCase{ctrl: ctrl}
	mock.recorder = &MockEventPublisherUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisherUseCase) EXPECT() *MockEventPublisherUseCaseMockRecorder {
	return m.recorder
}

// PublishEvent mocks base method.
func (m *MockEventPublisherUseCase) PublishEvent(ctx context.Context, userID string, req application.PublishEventRequest) (*domain.FeedEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishEvent", ctx, userID, req)
	ret0, _ := ret[0].(*domain.FeedEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishEvent indicates an expected call of PublishEvent.
func (mr *MockEventPublisherUseCaseMockRecorder) PublishEvent(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishEvent", reflect.TypeOf((*MockEventPublisherUseCase)(nil).PublishEvent), ctx, userID, req)
}
