// Code generated by MockGen. DO NOT EDIT.
// Source: real-time-activity-feed/internal/module/feed/application (interfaces: FeedUseCase)
//
// Generated by this command:
//
//	mockgen -destination=../adapters/mocks/feed_usecase_mock.go -package=mocks real-time-activity-feed/internal/module/feed/application FeedUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "real-time-activity-feed/internal/module/feed/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFeedUseCase is a mock of FeedUseCase interface.
type MockFeedUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockFeedUseCaseMockRecorder
	isgomock struct{}
}

// MockFeedUseCaseMockRecorder is the mock recorder for MockFeedUseCase.
type MockFeedUseCaseMockRecorder struct {
	mock *MockFeedUseCase
}

// NewMockFeedUseCase creates a new mock instance.
func NewMockFeedUseCase(ctrl *gomock.Controller) *MockFeedUseCase {
	mock := &MockFeedUseCase{ctrl: ctrl}
	mock.recorder = &MockFeedUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedUseCase) EXPECT() *MockFeedUseCaseMockRecorder {
	return m.recorder
}

// GetFeed mocks base method.
func (m *MockFeedUseCase) GetFeed(ctx context.Context, eventType, query string, limit, offset int64) ([]domain.FeedEvent, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeed", ctx, eventType, query, limit, offset)
	ret0, _ := ret[0].([]domain.FeedEvent)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetFeed indicates an expected call of GetFeed.
func (mr *MockFeedUseCaseMockRecorder) GetFeed(ctx, eventType, query, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeed", reflect.TypeOf((*MockFeedUseCase)(nil).GetFeed), ctx, eventType, query, limit, offset)
}

// SubscribeToFeedEvents mocks base method.
func (m *MockFeedUseCase) SubscribeToFeedEvents(ctx context.Context) (<-chan *domain.FeedEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeToFeedEvents", ctx)
	ret0, _ := ret[0].(<-chan *domain.FeedEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeToFeedEvents indicates an expected call of SubscribeToFeedEvents.
func (mr *MockFeedUseCaseMockRecorder) SubscribeToFeedEvents(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeToFeedEvents", reflect.TypeOf((*MockFeedUseCase)(nil).SubscribeToFeedEvents), ctx)
}
